package com.example.factsapp;

public class Facts {
    public static String[] getFacts()
    {
        return new String[]{
                "The Bee Hummingbird weighs less than a penny.",
                "The Hawaiian alphabet has only 12 letters.",
                "A ball of glass will bounce higher than a ball of rubber of the same size.",
                "The bullfrog is the only animal that never sleeps.",
                "Elephants are the only mammals that can't jump.",
                "The tongue is the fastest healing part of a human body.",
                "No word in the English language rhymes with month.",
                "When the moon is directly overhead, you weigh slightly less.",
                "The humming bird is the only bird that can fly backwards.",
                "The only continent without reptiles or snakes is Antarctica.",
                "Beavers were once the size of bears.",
                "Koalas and humans are the only animals with unique fingerprints.",
                "Honeybees navigate by using the Sun as a compass.",
                "Hawaii is the only U.S. state never to report a temperature of zero.",
                "Texas is the only state that permits residents to cast absentee ballots from space.",
                "The world's biggest pyramid is not in Egypt, but in Mexico.",
                "A rainbow can only be seen in the morning or late afternoon.",
                "The only one-syllabled U.S. state is Maine.",
                "The Basenji is a dog that yodels instead of barking.",
                "The number of times a cricket chirps in 15 seconds, plus 37, will give you the current air temperature.",
                "In the Middle Ages, chicken soup was considered an aphrodisiac.",
                "No two lip impressions are the same.",
                "The Statue of Liberty features 7 points in her crown- one for each of the continents.",
        "Maine produces more toothpicks than any other state in the U.S.",
            "The term 007 was derived from 20007, the home zip code of many Washington, D.C. agents.",
            "The official state gem of Washington is petrified wood.",
        "Chameleons can move both their eyes in different directions at the same time.",
            "The woodpecker can hammer wood up to 16 times per second.",
            "The Statue of Liberty wears a size 879 sandal.",
            "It is against the law to put pretzels in bags in Philadelphia.",
            "The average cat can jump 5 times as high as its tail is long.",
            "Spiny lobsters migrate in groups of 50 or more, forming a conga line on the ocean floor.",
            "The chicken is the closest living relative of Tyrannosaurus Rex.",
            "The human brain takes up 2% of human body weight but uses 20% of its energy.",
        "The praying mantis can turn its head 180 degrees.",
            "There are more chickens than people in the world.",
        "Some bears build nests in trees to sunbathe and rest.",
        "The middle finger has the fastest growing nail.",
        "The average person takes 23,000 breaths a day.",
            "Tug-of-war was an Olympic sport in the early 1900s.",
            "The bumblebee bat weighs less than a penny.",
            "Pound cake got its name from the original recipe which called for a pound of butter.",
        "Jousting is the official sport of Maryland.",
            "Squirrels lose more than half of the nuts they hide.",
            "The longest attack of hiccups lasted 68 years.",
            "A bolt of lightning can reach temperatures hotter than the sun.",
        "When grazing or resting, cows tend to align their bodies with the magnetic north and south poles.",
        "Each year, the Moon moves away from Earth by about four centimeters.",
            "The King of Hearts is the only king without a mustache.",
        "Forty is the only number whose letters are in alphabetical order.",
            "One is the only number with letters in reverse alphabetical order.",
        "DFW Airport in Texas is larger than the island of Manhattan.",
            "Miami installed the first ATM for inline skaters.",
        "Giraffes have the same number of vertebrae as humans: 7.",
        "Strawberries are actually members of the rose family.",
        "Venus is the only planet to rotate clockwise.",
        "The flamingo can only eat when its head is upside down.",
            "Adult humans are the only mammal that can't breathe and swallow at the same time.",
        "Mercury and Venus are the only planets in our solar system with no moon.",
        "The only thing that can scratch a diamond is a diamond.",
            "In the U.S., there is an official rock, paper, scissors league.",
            "There are more tigers owned by Americans than in the wild worldwide.",
            "The average dog can understand over 150 words.",
            "Blueberries are one of the only natural foods that are truly blue in color.",
            "Maine produces more wild blueberries than anywhere else in the world.",
        "75% of the U.S.’s tart cherries come from Michigan.",
        "Antarctica is home to the largest desert in the world.",
        "You can tell a turtle’s gender by the noise it makes. Males grunt and females hiss.",
            "The national animal of Scotland is the Unicorn.",
            "The ostrich produces a booming noise, often confused with a lion roar.",
            "Golf was the first sport to be played on the moon.",
        "A housefly hums in the key of F.",
        "The sun is actually white, but the earth’s atmosphere makes it appear yellow.",
        "A flipped coin is more likely to land on the side it started on.",
        "When a koala is born, it is about the size of a jelly bean.",
        "Water can boil and freeze at the same time.",
            "There are more trees on Earth than stars in the Milky Way galaxy.",
        "The 100 folds in a chef's hat represent the 100 ways to cook an egg.",
        "The tiny pocket in jeans was made for pocket watches.",
        "The Snapple name combines the words Snappy and Apple.",
            "Arachibutyrophobia is the fear of getting peanut butter stuck to the roof of your mouth.",
        "Both green and black tea come from leaves of the same tree."
        };
    }
}
